### PR TITLE
Migrate to null safety, fix fonts, minor bugfix

### PR DESCRIPTION
**Pull request by fritzlb**
-migrated to null safety in preparation for dart 3 migration. I did use the tool from google but had to change about 20 places where it produced compile errors. There might still be bugs/redundant null checks/other things that aren’t pretty with null safety I didn’t discover.
-replaced the fonts with an open alternative that looks identical but can be freely distributed
-fixed a bug that would crash covercycle.dart if the user’s song library only included one song

### CODE REVIEW

**Comment by fritzlb** [comment]
oh it would be good if someone tested if iOS compilation still works, I only tested android on a pretty slow device

**Comment by sakofchit** [comment]
works for me––thank you for doing this 🙏 , spotted a couple things 

- remove Helvetica from the pubspec.yaml and add the new font you found in there––else the font won't load

also not sure why this happened if it's at all related 🤔 

IMG_2171

**Comment by fritzlb** [comment]
I didn’t commit pubspec.yaml properly, sorry for the oversight. It‘s fixed now.
As for the other bug I hope it’s not related, I can’t reproduce it on my android. Is there any chance you could provide a log?

**Comment by fritzlb** [comment]
now dart3 is supported. There's a deprecation error:
`You are applying Flutter's main Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/go/flutter-gradle-plugin-apply`
I tried fixing that but got into dependency hell, it would require to update playify and idk anything about why that's included in our source and not a pub.dev dependency. Presumably there are some changes?
Anyway, for now this PR would close #31

**Comment by sakofchit** [comment]
lgtm! 

also don't worry about playify it's an old package that i modified to get apple music support to work previously. that package's been updated and we could probably remove the local version of playify and swap it with this at some point

https://pub.dev/packages/playify

**Pull request merged**
